### ISSUE TITLE
test data with records not observed in training data

### ISSUE THREAD

**Issue by Sandy4321** [sradc/MyNotebooks#1]
Do you code how to treat test data with records not observed in training data
This functionality is absent in scikit learn NB
Also do you make accessable probabilities
Lime predict_proba for logistics regression?

**Comment by sradc** [comment]
the final code block of the notebook contains a function that can cope with values not observed in the training data. However, the class needs to be modified to use it.

Another small modification would be needed to get the probabilities output. they are computed just before making the class predictoin.
